# sudo: false
# language: node_js
# node_js:
# - '12'
# branches:
#   only:
#   - master
# script: make travis
# deploy:
# - provider: script
#   skip_cleanup: true
#   script: make release
#   on:
#     branch: master
#     node_js: 12
# env:
#   global:
#   - secure: tqqx6Uv1BC2lJM1HZZ7w9mxjlq+k44cpmQMDwLlpXXhXIiw32alqN+3yept+XR+0xbuDieV4VEVt2N8B8MTr/OdAuARa19YJ7zog8QAW9mIJ6hR/RA2ZARsKdRtKXnMOCSTahs8AT7udhxi5FIOc+75bSDoDUYwF/ToLGsfU+KRcBGODZtNuae0aIw2dyXbVEHz9FtknZpVuJMATSjOYFDlJrjulmBFGP+gEdK6Ddy+G+yfH0J2I3VaXK8769iOwAujxfW2McHjEznPpMX6xzj7KduQTCXo7PzB8IkqZ2gJ1s8/1UV2+82Tv22htCqAS6Yoi3k2n2tSSF6JRJNEMVpX9JIwqvgsRerUcWQYINuvV1ulWa99JOCvSio2CV3EJg5ZItjxqsJtn5YeEkEHMGCI26sVOYX6EB6anFg5z95Br8Y37iip8SRECz8ee5qZa88oyjBNUttTWm1TTuHGC70+M2l+6uyf8cGp1CrFV+zSrYIuDrVPWY3SUmX6Z+ggmH6SE9JohzmXYPyGWb9Bs0RFH4j5Eqrig8OvLOEIQn9XQkNciJ1h0Md2RGnEpP8Nvm/JUCubnURizmZAd7Osto/QQ3f7lDaseSO8eJdH1eSCAdaJXqd9RPY4JQrTT6qKjHpRAXJusDZhKakJDqkL/D2zNMAzlm5FeoMnXpU4GuAw=
#   - secure: DS3dcyFntTOVNU4EwBLk1n286c0S8H83cY2qN+Rbh7QFyEkdOFLgBqnAYbOWmYpOnOaN0f8IJw70RbooQuWNzPR1NrRJBUGtFSLJBQ5SWWtru5f/iPKT3YctSiBLBUW28OQ6AZy7AWNl/YtaHE43/na3RUJpWlXhReqw4mvzY25gqkmBVvkAqnttuwBy5m2TyTayInGK0XjHQcxqN8QEZGvHIR6DnMYX+3d82O0hcGNqmUCV+gPMkeFALTHuLiS41WPCZ7Ii6sI5XQOmKn/DyTio5+owuvEYqCDglRvep2Tzw9MzFL+yxpGJ6cI4/vG9IwNfyuZ6UKGXHAqQAVjmJVRill0cv81KvQqaLXE2wWCjZrtVhp65UVj6UIIcGR36WQSnR09py9jo52wB/iBTsvZLyaplmqEsvbDFYvswx5Y9ktQDc5vDd72UtXVjROcU8/i0mKCv07PQn0FswkuDXprQtuAT6ou+ECei50QAzcJgoQ8vA64jlSEc7avn4GNrpCDvFv2OVEU/o9LyriVd1YCtV7RoFvhY6TaAqTU7xxQo2mP03iApr7VZF8QTWW0eX+gx9C5Ic+hLIe3HWnDSGeIyshS/u4zbeUEe5CxTlIHL8NOdZa1RlMBhMiqO06HxBy+KL7pzoP38rTm/UwNoeIp0RBIt6XmTYj3v1ihYGXU=
